apiVersion: v1
kind: Service
metadata:
  name: service-1st-app
  namespace: 1st-app-namespace
spec:
  selector:
    app: 1st-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
